### PR TITLE
Relax R version dependency

### PR DESCRIPTION
**Pull request by jonmcalder**
I'm not sure yet what the actual minimum requirements for CastleOfR are, but since swirl uses R (>=3.1.0) and you're using a similar callback strategy I assume this should be a safe minimum version for now?

### CODE REVIEW

**Comment by gsimchoni** [comment]
Thank you Jon, but I still would like to test it before merging (I agree, there's nothing here that even 2.1 didn't have, as far as I remember).

**Comment by jonmcalder** [comment]
Ok sure.

With regards to testing, I started working through the code last night and looked at adding some tests, but as you say in #2 it's not easy to test this as it is currently. Hopefully in some places we can look at breaking up some of the code into more testable functions, but that leaves us with a bit of a chicken and egg scenario i.e. refactoring without testing may break functionality, but it's probably not possible to test much without first refactoring. I guess there'll just need to be a lot of manual testing initially... you know best since you wrote it 😄

**Comment by gsimchoni** [comment]
Deeply sorry it took so long, Jon.

**Comment by jonmcalder** [comment]
No worries!

**Pull request merged**
